# build
# deploy to Azure as App service

name: Build Test Deploy BMI

env:
  AZURE_WEBAPP_NAME: gc-bmicalculator-ga            # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project

on:
  workflow_dispatch:                                # manually triggered

jobs:
  build:                                            # build for release
    name: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build for Release
      run: dotnet build --configuration Release
  
  test:                                             # run unit tests
    name: unit test
    needs: build                                    # run after build job
    runs-on: windows-latest                         
    steps:
    - name: Run unit tests
      run: dotnet test bmiUnitTestProject/bmiUnitTestProject.csproj --collect "Code coverage" 

