# Sonar cloud scan

name: Sonar
on:
  workflow_dispatch:                             

jobs:
  build_package:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build .
        projectKey: bmi2021multijob
        projectName: bmi2021multijob
        sonarOrganisation: gclynch
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# secrets.SONAR_TOKEN token in Github repo (generated when new project analysed on sonar cloud)
# 
